name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'firebase/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRAUG_REDIRECT }}'
          channelId: live
          projectId: fraug-redirect
